image: golang:1.17

stages:
  - test

test:
  stage: test
  except:
    refs:
      - tags
  before_script:
    - git config --global url."https://$GITLAB_USER:$GITLAB_ACCESS_TOKEN@gitlab.com/".insteadOf "https://gitlab.com/"
  script:
    - go test ./...
